version: '3.8'

services:
  api:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # network_mode: "host"
    container_name: api-dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 85:5055
      - 86:5056
      - 5172:5172
      # - 1401:1401
      - 1420:1420
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    restart: on-failure
